import Head from "next/head";
import {
  WalletModalButton,
  WalletMultiButton,
} from "@solana/wallet-adapter-react-ui";
import { useWallet } from "@solana/wallet-adapter-react";
import { useCallback, useEffect, useState } from "react";
import { PublicKey } from "@solana/web3.js";
import axios from "axios";
import { getCookie } from "cookies-next";

export async function getServerSideProps(context: any) {
  const discord_access = getCookie("discord_access", context);
  return {
    props: {
      discord_access: discord_access === undefined ? null : discord_access,
    },
  };
}

export default function Home({ discord_access }: { discord_access: any }) {
  const wallet = useWallet();
  const [userId, setUserId] = useState("");
  if (discord_access) {
    axios
      .get("https://discord.com/api/users/@me", {
        headers: {
          Authorization: `Bearer ${discord_access}`,
        },
      })
      .then((value) => setUserId(value.data.id.toString()));
  }

  const sendConnectedRequest = useCallback(
    async (key: PublicKey, userId: string) => {
      try {
        await axios.post("/api/connect", {
          walletAddress: key.toString(),
          userId,
        });
      } catch (error) {
        console.log(error);
      }
    },
    []
  );

  useEffect(() => {
    if (wallet.publicKey && userId) {
      sendConnectedRequest(wallet.publicKey, userId as string);
    }
  }, [sendConnectedRequest, wallet.publicKey, userId]);

  return (
    <>
      <Head>
        <title>Connect Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex items-center justify-center">
        {discord_access ? (
          <div>
            {!wallet.publicKey ? <WalletModalButton /> : <WalletMultiButton />}
          </div>
        ) : (
          <a
            className="p-5 bg-black text-white"
            href="https://discord.com/api/oauth2/authorize?client_id=1031396460979298354&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fdiscord%2Fcallback&response_type=code&scope=identify"
          >
            Login Discord
          </a>
        )}
      </main>
    </>
  );
}
