import Head from 'next/head'
import { WalletModalButton, WalletMultiButton } from '@solana/wallet-adapter-react-ui'
import { useWallet } from '@solana/wallet-adapter-react'
import { useCallback, useEffect } from 'react';
import { PublicKey } from '@solana/web3.js';
import axios from 'axios';
import { useRouter } from 'next/router'

export default function Home() {
  const wallet = useWallet();
  const router = useRouter();
  const { userId } = router.query;

  const sendConnectedRequest = useCallback(async (key: PublicKey, userId: string) => {
    try {
      await axios.post("/api/connect", {
        walletAddress: key.toString(),
        userId, // need to authorize using discord auth
      });
    } catch (error) {
      console.log(error);
    }
  }, []);

  useEffect(() => {
    if (wallet.publicKey && userId) {
      sendConnectedRequest(wallet.publicKey, userId as string);
    }
  }, [sendConnectedRequest, wallet.publicKey, userId]);

  return (
    <>
      <Head>
        <title>Connect Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex items-center justify-center">
        <div>
          {!wallet.publicKey ? <WalletModalButton /> : <WalletMultiButton />}
        </div>
      </main>
    </>
  )
}
